### PR TITLE
Enable descentralized counters

### PR DESCRIPTION
**Pull request by josevalim**

### CODE REVIEW

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:

**Comment by greg-rychlewski** [comment]
@josevalim Sorry to bug you. I read the article about decentralized counters after seeing this PR but I'm not 100% I understand what they are used for. Is this some kind of internal counter each ets table keeps to know how many times it has been updated?

**Comment by josevalim** [comment]
It is a counter storing how many entries in the table. But we never query its size. :)

**Comment by josevalim** [comment]
Also, you asking questions is never bugging me, I am always glad to transfer knowledge on anything Elixir/Ecto related :)

**Pull request merged**
